In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
data = 'winequality-red.csv.xlsx'
df = pd.read_csv("winequality-red.csv")
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [10]:
# Split data into training and testing sets
from sklearn.model_selection import train_test_split
x = df.drop('quality', axis=1)
y = df['quality']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1279, 11), (320, 11), (1279,), (320,))

In [13]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()


In [14]:
# Make predictions using the testing set
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
y_pred

array([5.41204216, 6.85601388, 5.34153137, 5.44122994, 5.20217596,
       6.75845533, 5.04871829, 4.80643614, 4.82271624, 6.75845533,
       5.18691925, 5.06514028, 5.34237911, 5.67587171, 5.80017712,
       5.60816809, 5.59272701, 5.32779632, 5.09448986, 6.12253306,
       6.16296373, 5.83086631, 5.1600252 , 5.34483851, 5.8611581 ,
       6.20260754, 5.74941824, 6.00230596, 5.81016354, 4.92964654,
       5.24527822, 5.50818826, 5.28552578, 5.14817734, 5.13866254,
       6.53249412, 5.82289104, 5.09356284, 5.8730281 , 6.02750419,
       5.40072131, 5.4202074 , 5.22241847, 6.25306426, 5.23448705,
       6.46630177, 6.11469365, 5.46854109, 4.63159447, 5.22850436,
       5.39541381, 5.13065016, 4.91372114, 6.0031832 , 4.96555516,
       5.69558816, 5.02098244, 4.89279869, 6.25396654, 5.22130093,
       4.89834731, 6.42749475, 5.87787449, 4.77178914, 5.3248253 ,
       6.35458755, 5.28758866, 6.42958235, 5.12241471, 5.93075895,
       6.45555603, 5.55510665, 5.84289328, 5.09184479, 5.24867

In [15]:
 # The coefficients
print('Coefficients: \n', regressor.coef_)

Coefficients: 
 [ 2.43398142e-02 -1.16044143e+00 -2.01706036e-01  1.68301382e-02
 -1.53993432e+00  3.73116795e-03 -2.95570312e-03 -2.00866070e+01
 -3.69540728e-01  8.46867418e-01  2.82668321e-01]


In [17]:
# The mean squared error
print("Mean squared error: %.2f"
        % np.mean((y_pred - y_test) ** 2))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % regressor.score(X_test, y_test))

# R^2 score
from sklearn.metrics import r2_score
print('R^2 score: %.2f' % r2_score(y_test, y_pred))

Mean squared error: 0.40
Variance score: 0.36
R^2 score: 0.36


In [18]:
from sklearn.preprocessing import StandardScaler
xscaler = StandardScaler()
yscaler = StandardScaler()
X_train_scaled = xscaler.fit_transform(X_train)
X_test_scaled = xscaler.fit_transform(X_test)


In [19]:
X_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1429            7.9             0.180         0.40             2.2      0.049   
688             7.7             0.660         0.04             1.6      0.039   
69              8.0             0.705         0.05             1.9      0.074   
403            11.4             0.600         0.49             2.7      0.085   
1570            6.4             0.360         0.53             2.2      0.230   
...             ...               ...          ...             ...        ...   
310            10.3             0.530         0.48             2.5      0.063   
116             8.3             0.540         0.28             1.9      0.077   
1076            9.9             0.320         0.56             2.0      0.073   
1495            7.0             0.430         0.02             1.9      0.080   
335            11.9             0.695         0.53             3.4      0.128   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1429                 38.0                  67.0  0.99600  3.33       0.93   
688                   4.0                   9.0  0.99620  3.40       0.47   
69                    8.0                  19.0  0.99620  3.34       0.95   
403                  10.0                  41.0  0.99940  3.15       0.63   
1570                 19.0                  35.0  0.99340  3.37       0.93   
...                   ...                   ...      ...   ...        ...   
310                   6.0                  25.0  0.99980  3.12       0.59   
116                  11.0                  40.0  0.99780  3.39       0.61   
1076                  3.0                   8.0  0.99534  3.15       0.73   
1495                 15.0                  28.0  0.99492  3.35       0.81   
335                   7.0                  21.0  0.99920  3.17       0.84   

      alcohol  
1429     11.3  
688       9.4  
69       10.5  
403      10.5  
1570     12.4  
...       ...  
310       9.3  
116      10.0  
1076     11.4  
1495     10.6  
335      12.2  

[1279 rows x 11 columns]

In [20]:
X_test_scaled

array([[ 0.31504241,  2.01658731, -0.74356593, ...,  0.90786113,
        -0.80088835,  0.9445763 ],
       [ 0.60810512, -1.52231138,  1.31965624, ..., -0.66178621,
         2.62372075,  1.3907889 ],
       [-0.62275825,  0.29100861,  0.13330349, ...,  1.03866507,
        -0.40790042, -0.21557646],
       ...,
       [ 1.25284307, -0.11845074,  1.88704233, ..., -1.3812079 ,
        -0.01491249,  1.21230386],
       [-0.32969555,  0.17402023, -0.4340826 , ...,  0.18843943,
        -0.68860608, -0.8402741 ],
       [ 0.25642987, -0.35242751,  1.11333402, ..., -0.07316846,
        -0.35175929, -0.57254654]])

In [24]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [25]:
reg_lassso = Lasso(alpha=0.1)
reg_lassso.fit(X_train, y_train)
y_pred_lasso = reg_lassso.predict(X_train)
y_pred_lasso

array([5.90660351, 5.4004309 , 5.68269948, ..., 5.97632012, 5.69455715,
       6.21504264])

In [26]:
reg_lassso.score(X_train, y_train)

0.23790765165827832

In [27]:
reg_ridge = Ridge()
reg_ridge.fit(X_train, y_train)
y_pred_ridge = reg_ridge.predict(X_train)
y_pred_ridge

array([6.52261983, 5.12396342, 5.73891125, ..., 6.3109661 , 5.97620726,
       6.14856019])

In [28]:
reg_ridge.score(X_train, y_train)

0.3564008808414514